# Generated by Django 6.1 on 2026-09-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='timetable_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], default='student', max_length=20),
        ),
    ]
