# Generated by Django 6.1 on 2026-09-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_timetable_timetable_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='classroom',
            field=models.CharField(default='Not Assigned', max_length=50),
        ),
    ]
